version: '3'

networks:
  red:
    driver: bridge

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - red
    volumes:
      #- /db/:/var/lib/mysql
      - /mnt/d/baseDatos/datos/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    networks:
      - red
    # volumes:
    #   - /loud/:/var/www/html
    - /mnt/d/baseDatos/config/:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.0.84
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=0704@Valen
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      
